name: 'LAPRAS Card Readme'
description: 'Add LAPRAS Card to your GitHub profile.'
author: 'kawamataryo'
inputs:
  GH_TOKEN:
    default: ${{ github.token }}
    required: false
    description: 'GitHub Token'
  SHARE_ID:
    required: true
    description: 'lapras public share id'
  README_FILE:
    required: false
    description: 'your repository readme file name'
    default: 'README.md'
  ICON_FIRST:
    required: false
    description: 'icon color 1'
    default: '#030E21'
  ICON_SECOND:
    required: false
    description: 'icon color 2'
    default: '#1688BF'
  BACKGROUND_FIRST:
    required: false
    description: 'background color 1'
    default: '#020E27'
  BACKGROUND_SECOND:
    required: false
    description: 'background color 2'
    default: '#0E5593'
  LANG:
    required: false
    description: 'language'
    default: 'ja'
  CARD_WIDTH:
    required: false
    description: 'card width'
    default: '400'
  UPDATE_TIME:
    required: false
    description: 'display of score update date and time'
    default: 'true'
  IS_CENTER:
    required: false
    description: 'Determines if the image is centered in the readme'
    default: 'false'
  ALTERNATIVE_TEXT:
    required: false
    description: 'Alternative text for LAPRAS Card, crucial for enhancing accessibility for screen reader users'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: "credit-card"
  color: "blue"
